/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import aplicacion.de.evaluacion.de.proyectos.Tabla;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Enzo
 */
public class EBITDA extends javax.swing.JFrame {

    /**
     * Creates new form EBITDA
     */
    private File ebitda = new File("C:\\Project evaluator\\ebitda.txt");
    private String[] datosing;
    private String[] datoseg;

    public EBITDA() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //determina el color del fondo
        Color c = new Color(56, 80, 113);
        getContentPane().setBackground(c);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EBITDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EBITDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EBITDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EBITDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EBITDA().setVisible(true);
               
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtebitda = new javax.swing.JLabel();
        scroll_ebitda = new javax.swing.JScrollPane();
        tabla_ebitda = new javax.swing.JTable();
        btn_añadirfila_ebi = new javax.swing.JButton();
        btn_quitarfila_ebi = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EBITDA");
        setBackground(new java.awt.Color(240, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(900, 690));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        txtebitda.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        txtebitda.setForeground(new java.awt.Color(240, 255, 255));
        txtebitda.setText("EBITDA");

        tabla_ebitda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Conceptos y Descripciones"
            }
        ));
        tabla_ebitda.setShowGrid(true);
        tabla_ebitda.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tabla_ebitdaMouseMoved(evt);
            }
        });
        tabla_ebitda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabla_ebitdaFocusGained(evt);
            }
        });
        tabla_ebitda.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabla_ebitdaPropertyChange(evt);
            }
        });
        scroll_ebitda.setViewportView(tabla_ebitda);

        btn_añadirfila_ebi.setText("añadir fila");
        btn_añadirfila_ebi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirfila_ebiActionPerformed(evt);
            }
        });

        btn_quitarfila_ebi.setText("quitar fila");
        btn_quitarfila_ebi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarfila_ebiActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll_ebitda)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtebitda, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(312, 312, 312)
                        .addComponent(btn_añadirfila_ebi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_quitarfila_ebi)
                        .addGap(87, 87, 87)
                        .addComponent(btn_guardar)
                        .addContainerGap(7, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtebitda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_añadirfila_ebi)
                    .addComponent(btn_quitarfila_ebi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll_ebitda, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void set_ing(String[] datos_ing) {
        datosing = datos_ing;
    }

    public void set_eg(String[] datos_eg) {
        datoseg = datos_eg;
    }

    public void filas_datos_ebitda() {
        System.out.println("Ebitda modificado");
        Tabla.get_modelo(tabla_ebitda).setRowCount(0);
        try {
            datosing[0] = String.valueOf("Ingresos");
            datoseg[0] = String.valueOf("Egresos");
        } catch (NullPointerException e) {

        }
        Tabla.get_modelo(tabla_ebitda).addRow(datosing);
        Tabla.get_modelo(tabla_ebitda).addRow(datoseg);
    }

    public File getEbitda() {
        return ebitda;
    }

    public JTable getTabla_ebitda() {
        return tabla_ebitda;
    }


    private void btn_añadirfila_ebiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirfila_ebiActionPerformed
        // TODO add your handling code here
        //Añade filas a ebitda
        Vector<?> rowData = null;
        Tabla.get_modelo(tabla_ebitda).addRow(rowData);
    }//GEN-LAST:event_btn_añadirfila_ebiActionPerformed

    private void btn_quitarfila_ebiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarfila_ebiActionPerformed
        // TODO add your handling code here:
        //Quita filas a idicadores, si no se selecciona una fila,se elimina la ultima

        if (tabla_ebitda.getSelectedRowCount() == 1) {
            Tabla.get_modelo(tabla_ebitda).removeRow(tabla_ebitda.getSelectedRow());
        } else {
            Tabla.get_modelo(tabla_ebitda).removeRow(tabla_ebitda.getRowCount() - 1);
        }
    }//GEN-LAST:event_btn_quitarfila_ebiActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        try {
            Tabla.exportar(ebitda, tabla_ebitda);
            JOptionPane.showMessageDialog(null, "datos guardados");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al guardar los datos");
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void tabla_ebitdaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabla_ebitdaFocusGained
        // TODO add your handling code here:


    }//GEN-LAST:event_tabla_ebitdaFocusGained

    private void tabla_ebitdaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabla_ebitdaPropertyChange
        // TODO add your handling code here:
        filas_datos_ebitda();

    }//GEN-LAST:event_tabla_ebitdaPropertyChange

    private void tabla_ebitdaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_ebitdaMouseMoved
        // TODO add your handling code here:
        filas_datos_ebitda();
    }//GEN-LAST:event_tabla_ebitdaMouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        filas_datos_ebitda();
    }//GEN-LAST:event_formMouseMoved
    private void tabla_ingresosPropertyChange(java.beans.PropertyChangeEvent evt) {
        // TODO add your handling code here:

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadirfila_ebi;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_quitarfila_ebi;
    private javax.swing.JScrollPane scroll_ebitda;
    private javax.swing.JTable tabla_ebitda;
    private javax.swing.JLabel txtebitda;
    // End of variables declaration//GEN-END:variables
}
