/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import aplicacion.de.evaluacion.de.proyectos.Tabla;
import java.awt.Color;
import java.io.File;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enzo
 */
public class Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    private File directorio = new File("C:\\Project evaluator\\sueldos");

    public Empleados() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //determina el color del fondo
        Color c = new Color(56, 80, 113);
        getContentPane().setBackground(c);
        directorio.mkdirs();

    }

    public void importar_emp() {
        //importa la tabla correspondiente al combo
        for (int i = 1; i <= Principal.longevidad; i++) {
            if (combo_años.getSelectedIndex() + 1 == i) {
                File sueldos = new File("C:\\Project evaluator\\sueldos\\sueldos " + i + ".txt");
                Tabla.importar(sueldos, tabla_sueldos);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsueldos = new javax.swing.JLabel();
        scroll_ebitda = new javax.swing.JScrollPane();
        tabla_sueldos = new javax.swing.JTable();
        total_sueldos = new javax.swing.JTextField();
        txttotalsueldos = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        combo_años = new javax.swing.JComboBox<>();
        btn_añadirfila_emp = new javax.swing.JButton();
        btn_quitarfila_emp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleados");
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(900, 690));

        txtsueldos.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        txtsueldos.setForeground(new java.awt.Color(240, 255, 255));
        txtsueldos.setText("Sueldos");

        tabla_sueldos.setBackground(new java.awt.Color(255, 255, 255));
        tabla_sueldos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre y apellido", "Basico Jornada  Completa", "Comision  ", "Total Sueldo  ", "Antiguedad  ", "Ad/ Antiguedad  ", "Ad/Presentismo ", "Bruto  ", "Jubiliacion", "Obra Social ", "Ley 19032 ", "SEC ", "Total descuentos", "Total neto"
            }
        ));
        tabla_sueldos.setShowGrid(true);
        scroll_ebitda.setViewportView(tabla_sueldos);

        total_sueldos.setEditable(false);
        total_sueldos.setBackground(new java.awt.Color(255, 255, 255));

        txttotalsueldos.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txttotalsueldos.setText("Total sueldos");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        combo_años.setMaximumRowCount(5);
        combo_años.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_añosItemStateChanged(evt);
            }
        });
        combo_años.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_añosMouseClicked(evt);
            }
        });
        combo_años.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_añosActionPerformed(evt);
            }
        });

        btn_añadirfila_emp.setText("añadir fila");
        btn_añadirfila_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirfila_empActionPerformed(evt);
            }
        });

        btn_quitarfila_emp.setText("quitar fila");
        btn_quitarfila_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarfila_empActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtsueldos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(combo_años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txttotalsueldos, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(total_sueldos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(btn_añadirfila_emp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_quitarfila_emp)
                        .addGap(40, 40, 40)
                        .addComponent(btn_guardar)
                        .addGap(67, 67, 67))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(scroll_ebitda, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txttotalsueldos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_sueldos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_añadirfila_emp)
                    .addComponent(btn_quitarfila_emp)
                    .addComponent(btn_guardar)
                    .addComponent(txtsueldos))
                .addGap(136, 136, 136)
                .addComponent(scroll_ebitda, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTabla_sueldos() {
        return tabla_sueldos;
    }


    private void combo_añosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_añosActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_combo_añosActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:  
        //exporta las tablas de sueldo a la carpeta
        try {
            for (int i = 1; i <= Principal.longevidad; i++) {
                if (combo_años.getSelectedIndex() + 1 == i) {
                    File sueldos = new File("C:\\Project evaluator\\sueldos\\sueldos " + i + ".txt");
                    Tabla.exportar(sueldos, tabla_sueldos);
                }
            }
            JOptionPane.showMessageDialog(null, "datos guardados");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al guardar los datos");
        }


    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_añadirfila_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirfila_empActionPerformed
        // TODO add your handling code here
        //Añade filas a imp
        DefaultTableModel tblmodel = (DefaultTableModel) tabla_sueldos.getModel();
        Vector<?> rowData = null;
        tblmodel.addRow(rowData);
    }//GEN-LAST:event_btn_añadirfila_empActionPerformed

    private void btn_quitarfila_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarfila_empActionPerformed
        // TODO add your handling code here:
        //Quita filas a imp, si no se selecciona una fila,se elimina la ultima
        DefaultTableModel tblmodel = (DefaultTableModel) tabla_sueldos.getModel();
        if (tabla_sueldos.getSelectedRowCount() == 1) {
            tblmodel.removeRow(tabla_sueldos.getSelectedRow());
        } else {
            tblmodel.removeRow(tabla_sueldos.getRowCount() - 1);
        }
    }//GEN-LAST:event_btn_quitarfila_empActionPerformed

    private void combo_añosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_añosMouseClicked
        // TODO add your handling code here:
        try {
            File sueldos = new File("C:\\Project evaluator\\sueldos\\sueldos " + (int) (combo_años.getSelectedIndex() + 1) + ".txt");
            Tabla.exportar(sueldos, tabla_sueldos);

        } catch (Exception e) {

        }

    }//GEN-LAST:event_combo_añosMouseClicked

    private void combo_añosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_añosItemStateChanged
        // TODO add your handling code here:
        
        //borra las filas de la tabla de la interfaz

        DefaultTableModel tblmodel = (DefaultTableModel) tabla_sueldos.getModel();
        tblmodel.setRowCount(0);

        //importa la nueva tabla
        importar_emp();
        if (tabla_sueldos.getRowCount() == 0) {
            tblmodel.setRowCount(30);
        }
    }//GEN-LAST:event_combo_añosItemStateChanged
    
    public void inicializar_combo() {

        for (int i = 1; i <= Principal.longevidad; i++) {
            combo_años.addItem("Año " + i);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });

        //añade filas a la tabla si no tiene ninguna
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadirfila_emp;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_quitarfila_emp;
    private javax.swing.JComboBox<String> combo_años;
    private javax.swing.JScrollPane scroll_ebitda;
    private javax.swing.JTable tabla_sueldos;
    private javax.swing.JTextField total_sueldos;
    private javax.swing.JLabel txtsueldos;
    private javax.swing.JLabel txttotalsueldos;
    // End of variables declaration//GEN-END:variables
}
