/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import aplicacion.de.evaluacion.de.proyectos.Tabla;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enzo
 */
public class Impuestos extends javax.swing.JFrame {

    /**
     * Creates new form Impuestos
     */
    //declara el archivo a importar o exportar por los métodos de Tabla
    private File impuestos = new File("C:\\Project evaluator\\impuestos.txt");
    private File indimpuestos = new File("C:\\Project evaluator\\indicadores impuestos.txt");

    public Impuestos() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //determina el color del fondo
        Color c = new Color(56, 80, 113);
        getContentPane().setBackground(c);

    }

    public JTable getTabla_impuestos() {
        return tabla_impuestos;
    }

    public JTable getTabla_indimpuestos() {
        return tabla_indimpuestos;
    }

    public File getImpuestos() {
        return impuestos;
    }

    public File getIndimpuestos() {
        return indimpuestos;
    }

    public void filas_datos(JTable tablaimp, JTable tablaindimp) {
        //inicializa los datos de las filas de la tabla
        if (tablaimp.getRowCount() < 1) {

            DefaultTableModel tblmodel = (DefaultTableModel) tabla_impuestos.getModel();
            String dato1[] = {"Impuesto a las ganancias"};
            String dato2[] = {"IVA Ventas"};
            String dato3[] = {"IVA Compras"};
            String dato4[] = {"Montotributo/RI"};
            String dato5[] = {"Ingresos Brutos"};
            String dato6[] = {"Total de impuestos"};
            tblmodel.addRow(dato1);
            tblmodel.addRow(dato2);
            tblmodel.addRow(dato3);
            tblmodel.addRow(dato4);
            tblmodel.addRow(dato5);
            tblmodel.addRow(dato6);
            Tabla.filas_defecto(tablaimp, 10);
        }

        //inicializa los datos de las filas de la tabla
        if (tablaindimp.getRowCount() < 1) {

            DefaultTableModel tblmodel2 = (DefaultTableModel) tabla_indimpuestos.getModel();
            String dato1[] = {"Tasa de descuento"};
            String dato2[] = {"Tasa de interés"};
            String dato3[] = {"Tasa de crecimiento de la población"};
            String dato4[] = {"Inflación Mensual"};
            String dato5[] = {"Inflación Anual"};
            String dato6[] = {"Ingresos Brutos"};
            String dato7[] = {"IVA"};
            String dato8[] = {"Ganancias"};
            String dato9[] = {"Contribuciones patronales"};
            String dato10[] = {"Obra Social"};

            tblmodel2.addRow(dato1);
            tblmodel2.addRow(dato2);
            tblmodel2.addRow(dato3);
            tblmodel2.addRow(dato4);
            tblmodel2.addRow(dato5);
            tblmodel2.addRow(dato6);
            tblmodel2.addRow(dato7);
            tblmodel2.addRow(dato8);
            tblmodel2.addRow(dato9);
            tblmodel2.addRow(dato10);
            Tabla.filas_defecto(tablaindimp, 10);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtimpuestos = new javax.swing.JLabel();
        scroll_impuestos = new javax.swing.JScrollPane();
        tabla_impuestos = new javax.swing.JTable();
        btn_añadirfila_imp = new javax.swing.JButton();
        btn_quitarfila_imp = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        scroll_indimpuestos = new javax.swing.JScrollPane();
        tabla_indimpuestos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Impuestos");
        setBackground(new java.awt.Color(240, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(900, 690));

        txtimpuestos.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        txtimpuestos.setForeground(new java.awt.Color(240, 255, 255));
        txtimpuestos.setText("Impuestos");

        tabla_impuestos.setBackground(new java.awt.Color(255, 255, 255));
        tabla_impuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "impuesto"
            }
        ));
        tabla_impuestos.setShowGrid(true);
        scroll_impuestos.setViewportView(tabla_impuestos);

        btn_añadirfila_imp.setText("añadir fila");
        btn_añadirfila_imp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirfila_impActionPerformed(evt);
            }
        });

        btn_quitarfila_imp.setText("quitar fila");
        btn_quitarfila_imp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarfila_impActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        tabla_indimpuestos.setBackground(new java.awt.Color(255, 255, 255));
        tabla_indimpuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Indicador", "Valor"
            }
        ));
        tabla_indimpuestos.setShowGrid(true);
        scroll_indimpuestos.setViewportView(tabla_indimpuestos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtimpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(436, 436, 436)
                        .addComponent(btn_añadirfila_imp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_quitarfila_imp)
                        .addGap(87, 87, 87)
                        .addComponent(btn_guardar))
                    .addComponent(scroll_indimpuestos)
                    .addComponent(scroll_impuestos))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_añadirfila_imp)
                    .addComponent(btn_quitarfila_imp)
                    .addComponent(txtimpuestos))
                .addGap(19, 19, 19)
                .addComponent(scroll_impuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll_indimpuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_añadirfila_impActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirfila_impActionPerformed
        // TODO add your handling code here
        //Añade filas a imp
        DefaultTableModel tblmodel = (DefaultTableModel) tabla_impuestos.getModel();
        Vector<?> rowData = null;
        tblmodel.addRow(rowData);
    }//GEN-LAST:event_btn_añadirfila_impActionPerformed

    private void btn_quitarfila_impActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarfila_impActionPerformed
        // TODO add your handling code here:
        //Quita filas a imp, si no se selecciona una fila,se elimina la ultima
        DefaultTableModel tblmodel = (DefaultTableModel) tabla_impuestos.getModel();
        if (tabla_impuestos.getSelectedRowCount() == 1) {
            tblmodel.removeRow(tabla_impuestos.getSelectedRow());
        } else {
            tblmodel.removeRow(tabla_impuestos.getRowCount() - 1);
        }
    }//GEN-LAST:event_btn_quitarfila_impActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        try {
            File impuestos = new File("C:\\Project evaluator\\impuestos.txt");
            File indimpuestos = new File("C:\\Project evaluator\\indicadores impuestos.txt");
            JTable tablaimp = getTabla_impuestos();
            JTable tablaindimp = getTabla_indimpuestos();
            Tabla.exportar(impuestos, tablaimp);
            Tabla.exportar(indimpuestos, tablaindimp);
            JOptionPane.showMessageDialog(null, "datos guardados");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al guardar los datos");
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impuestos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadirfila_imp;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_quitarfila_imp;
    private javax.swing.JScrollPane scroll_impuestos;
    private javax.swing.JScrollPane scroll_indimpuestos;
    private javax.swing.JTable tabla_impuestos;
    private javax.swing.JTable tabla_indimpuestos;
    private javax.swing.JLabel txtimpuestos;
    // End of variables declaration//GEN-END:variables
}
