/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import aplicacion.de.evaluacion.de.proyectos.Tabla;
import static com.sun.tools.javac.tree.TreeInfo.args;
import java.awt.Color;
import java.io.File;
import javax.lang.model.SourceVersion;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enzo
 */
public class Principal extends javax.swing.JFrame {

    public static int longevidad = 5;
    public static boolean import_ingeg = false;
    private Indicadores indicadores = new Indicadores();
    private Empleados empleados = new Empleados();
    private Credito credito = new Credito();
    private Impuestos impuestos = new Impuestos();
    private EBITDA ebitda = new EBITDA();
    private IngVsGas ingvsgas = new IngVsGas(ebitda, impuestos);
    private Riesgo riesgo = new Riesgo();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtañosvida = new javax.swing.JLabel();
        txtnombreproyecto = new javax.swing.JLabel();
        nombreproyecto = new javax.swing.JTextField();
        añosvida = new javax.swing.JTextField();
        panel_negro = new javax.swing.JPanel();
        panel_IngVsGas = new javax.swing.JPanel();
        btn_IngVsGas = new javax.swing.JButton();
        panel_indicadores = new javax.swing.JPanel();
        btn_indicadores = new javax.swing.JButton();
        panel_empleados = new javax.swing.JPanel();
        btn_empleados = new javax.swing.JButton();
        panel_impuestos = new javax.swing.JPanel();
        btn_impuestos = new javax.swing.JButton();
        panel_credito = new javax.swing.JPanel();
        btn_credito = new javax.swing.JButton();
        panel_riesgo = new javax.swing.JPanel();
        btn_riesgo = new javax.swing.JButton();
        panel_EBITDA = new javax.swing.JPanel();
        btn_EBITDA = new javax.swing.JButton();
        panel_azul = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        panel_azul_oscuro = new javax.swing.JPanel();
        JLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(773, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtañosvida.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtañosvida.setText("Longevidad del proyecto");
        getContentPane().add(txtañosvida, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        txtnombreproyecto.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtnombreproyecto.setText("Nombre del proyecto");
        getContentPane().add(txtnombreproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));
        getContentPane().add(nombreproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 210, 30));

        añosvida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añosvidaActionPerformed(evt);
            }
        });
        añosvida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                añosvidaPropertyChange(evt);
            }
        });
        getContentPane().add(añosvida, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 210, 30));

        panel_negro.setBackground(new java.awt.Color(0, 0, 0));

        panel_IngVsGas.setBackground(new java.awt.Color(0, 0, 0));
        panel_IngVsGas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_IngVsGasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_IngVsGasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_IngVsGasMouseExited(evt);
            }
        });

        btn_IngVsGas.setBackground(new java.awt.Color(0, 0, 0));
        btn_IngVsGas.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        btn_IngVsGas.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngVsGas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ingresos_y_Egresos.png"))); // NOI18N
        btn_IngVsGas.setText("Ingresos y Egresos");
        btn_IngVsGas.setBorder(null);
        btn_IngVsGas.setBorderPainted(false);
        btn_IngVsGas.setContentAreaFilled(false);
        btn_IngVsGas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_IngVsGas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_IngVsGasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_IngVsGasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_IngVsGasMouseExited(evt);
            }
        });
        btn_IngVsGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngVsGasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_IngVsGasLayout = new javax.swing.GroupLayout(panel_IngVsGas);
        panel_IngVsGas.setLayout(panel_IngVsGasLayout);
        panel_IngVsGasLayout.setHorizontalGroup(
            panel_IngVsGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_IngVsGasLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(btn_IngVsGas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_IngVsGasLayout.setVerticalGroup(
            panel_IngVsGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_IngVsGas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panel_indicadores.setBackground(new java.awt.Color(0, 0, 0));
        panel_indicadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_indicadoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_indicadoresMouseExited(evt);
            }
        });

        btn_indicadores.setBackground(new java.awt.Color(0, 0, 0));
        btn_indicadores.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        btn_indicadores.setForeground(new java.awt.Color(255, 255, 255));
        btn_indicadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icono_indicadores.png"))); // NOI18N
        btn_indicadores.setText("Indicadores");
        btn_indicadores.setBorder(null);
        btn_indicadores.setBorderPainted(false);
        btn_indicadores.setContentAreaFilled(false);
        btn_indicadores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_indicadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_indicadoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_indicadoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_indicadoresMouseExited(evt);
            }
        });
        btn_indicadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_indicadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_indicadoresLayout = new javax.swing.GroupLayout(panel_indicadores);
        panel_indicadores.setLayout(panel_indicadoresLayout);
        panel_indicadoresLayout.setHorizontalGroup(
            panel_indicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_indicadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_indicadores, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_indicadoresLayout.setVerticalGroup(
            panel_indicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_indicadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panel_empleados.setBackground(new java.awt.Color(0, 0, 0));
        panel_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_empleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_empleadosMouseExited(evt);
            }
        });

        btn_empleados.setBackground(new java.awt.Color(0, 0, 0));
        btn_empleados.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        btn_empleados.setForeground(new java.awt.Color(255, 255, 255));
        btn_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono empleados.png"))); // NOI18N
        btn_empleados.setText("Empleados");
        btn_empleados.setBorder(null);
        btn_empleados.setBorderPainted(false);
        btn_empleados.setContentAreaFilled(false);
        btn_empleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_empleadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_empleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_empleadosMouseExited(evt);
            }
        });
        btn_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_empleadosLayout = new javax.swing.GroupLayout(panel_empleados);
        panel_empleados.setLayout(panel_empleadosLayout);
        panel_empleadosLayout.setHorizontalGroup(
            panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_empleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_empleadosLayout.setVerticalGroup(
            panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_empleados, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panel_impuestos.setBackground(new java.awt.Color(0, 0, 0));
        panel_impuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_impuestosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_impuestosMouseExited(evt);
            }
        });

        btn_impuestos.setBackground(new java.awt.Color(0, 0, 0));
        btn_impuestos.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        btn_impuestos.setForeground(new java.awt.Color(255, 255, 255));
        btn_impuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono impuestos.png"))); // NOI18N
        btn_impuestos.setText("Impuestos");
        btn_impuestos.setBorder(null);
        btn_impuestos.setBorderPainted(false);
        btn_impuestos.setContentAreaFilled(false);
        btn_impuestos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_impuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_impuestosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_impuestosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_impuestosMouseExited(evt);
            }
        });
        btn_impuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_impuestosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_impuestosLayout = new javax.swing.GroupLayout(panel_impuestos);
        panel_impuestos.setLayout(panel_impuestosLayout);
        panel_impuestosLayout.setHorizontalGroup(
            panel_impuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_impuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_impuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
        );
        panel_impuestosLayout.setVerticalGroup(
            panel_impuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_impuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panel_credito.setBackground(new java.awt.Color(0, 0, 0));
        panel_credito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_creditoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_creditoMouseExited(evt);
            }
        });

        btn_credito.setBackground(new java.awt.Color(0, 0, 0));
        btn_credito.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        btn_credito.setForeground(new java.awt.Color(255, 255, 255));
        btn_credito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_credito.png"))); // NOI18N
        btn_credito.setBorder(null);
        btn_credito.setBorderPainted(false);
        btn_credito.setContentAreaFilled(false);
        btn_credito.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_credito.setLabel("Crédito");
        btn_credito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_creditoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_creditoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_creditoMouseExited(evt);
            }
        });
        btn_credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_creditoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_creditoLayout = new javax.swing.GroupLayout(panel_credito);
        panel_credito.setLayout(panel_creditoLayout);
        panel_creditoLayout.setHorizontalGroup(
            panel_creditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_creditoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_credito, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_creditoLayout.setVerticalGroup(
            panel_creditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_credito, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panel_riesgo.setBackground(new java.awt.Color(0, 0, 0));
        panel_riesgo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_riesgoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_riesgoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_riesgoMouseExited(evt);
            }
        });

        btn_riesgo.setBackground(new java.awt.Color(0, 0, 0));
        btn_riesgo.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        btn_riesgo.setForeground(new java.awt.Color(255, 255, 255));
        btn_riesgo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono riesgo.png"))); // NOI18N
        btn_riesgo.setActionCommand("Riesgo");
        btn_riesgo.setBorder(null);
        btn_riesgo.setBorderPainted(false);
        btn_riesgo.setContentAreaFilled(false);
        btn_riesgo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_riesgo.setLabel("Riesgo");
        btn_riesgo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_riesgoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_riesgoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_riesgoMouseExited(evt);
            }
        });
        btn_riesgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_riesgoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_riesgoLayout = new javax.swing.GroupLayout(panel_riesgo);
        panel_riesgo.setLayout(panel_riesgoLayout);
        panel_riesgoLayout.setHorizontalGroup(
            panel_riesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(panel_riesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_riesgoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panel_riesgoLayout.setVerticalGroup(
            panel_riesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(panel_riesgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btn_riesgo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        panel_EBITDA.setBackground(new java.awt.Color(0, 0, 0));
        panel_EBITDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_EBITDAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_EBITDAMouseExited(evt);
            }
        });

        btn_EBITDA.setBackground(new java.awt.Color(0, 0, 0));
        btn_EBITDA.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        btn_EBITDA.setForeground(new java.awt.Color(255, 255, 255));
        btn_EBITDA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_Ebitda.png"))); // NOI18N
        btn_EBITDA.setText("EBITDA");
        btn_EBITDA.setAlignmentX(0.5F);
        btn_EBITDA.setBorder(null);
        btn_EBITDA.setBorderPainted(false);
        btn_EBITDA.setContentAreaFilled(false);
        btn_EBITDA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_EBITDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EBITDAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EBITDAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EBITDAMouseExited(evt);
            }
        });
        btn_EBITDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EBITDAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_EBITDALayout = new javax.swing.GroupLayout(panel_EBITDA);
        panel_EBITDA.setLayout(panel_EBITDALayout);
        panel_EBITDALayout.setHorizontalGroup(
            panel_EBITDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EBITDALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_EBITDA, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_EBITDALayout.setVerticalGroup(
            panel_EBITDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_EBITDA, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_negroLayout = new javax.swing.GroupLayout(panel_negro);
        panel_negro.setLayout(panel_negroLayout);
        panel_negroLayout.setHorizontalGroup(
            panel_negroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_negroLayout.createSequentialGroup()
                .addGroup(panel_negroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_negroLayout.createSequentialGroup()
                        .addGroup(panel_negroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_credito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_impuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel_IngVsGas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_negroLayout.createSequentialGroup()
                        .addGroup(panel_negroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_indicadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_EBITDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_negroLayout.setVerticalGroup(
            panel_negroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_negroLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(panel_IngVsGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_EBITDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_indicadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_impuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_credito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        getContentPane().add(panel_negro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 590));

        panel_azul.setBackground(new java.awt.Color(56, 80, 113));

        txtTitulo.setBackground(new java.awt.Color(204, 204, 204));
        txtTitulo.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(85, 135, 184));
        txtTitulo.setText("Project Evaluator");

        panel_azul_oscuro.setBackground(new java.awt.Color(37, 53, 75));

        javax.swing.GroupLayout panel_azul_oscuroLayout = new javax.swing.GroupLayout(panel_azul_oscuro);
        panel_azul_oscuro.setLayout(panel_azul_oscuroLayout);
        panel_azul_oscuroLayout.setHorizontalGroup(
            panel_azul_oscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        panel_azul_oscuroLayout.setVerticalGroup(
            panel_azul_oscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_azulLayout = new javax.swing.GroupLayout(panel_azul);
        panel_azul.setLayout(panel_azulLayout);
        panel_azulLayout.setHorizontalGroup(
            panel_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_azulLayout.createSequentialGroup()
                .addComponent(panel_azul_oscuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        panel_azulLayout.setVerticalGroup(
            panel_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_azulLayout.createSequentialGroup()
                .addComponent(panel_azul_oscuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panel_azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 50));

        JLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_azul.jpg"))); // NOI18N
        JLabelFondo.setMaximumSize(new java.awt.Dimension(773, 630));
        JLabelFondo.setMinimumSize(new java.awt.Dimension(773, 630));
        getContentPane().add(JLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Impuestos getImpuestos() {
        return impuestos;
    }

    private void btn_IngVsGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngVsGasActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btn_IngVsGasActionPerformed

    private void btn_IngVsGasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IngVsGasMouseClicked
        // TODO add your handling code here:

        ((DefaultTableModel) ingvsgas.getTabla_ingresos().getModel()).setRowCount(0);
        ((DefaultTableModel) ingvsgas.getTabla_egresos().getModel()).setRowCount(0);

        //inicializa ing y eg
        Tabla.inicializar(ingvsgas.getTabla_ingresos());
        Tabla.inicializar(ingvsgas.getTabla_egresos());

        //imp ing eg con iva
        ingvsgas.getjComboBoxivaing().setSelectedItem("Con IVA");
        ingvsgas.getjComboBoxivaeg().setSelectedItem("Con IVA");
        ((DefaultTableModel) ingvsgas.getTabla_ingresos().getModel()).setRowCount(0);
        ((DefaultTableModel) ingvsgas.getTabla_egresos().getModel()).setRowCount(0);

        //imp ing y eg
        ingvsgas.getjComboBoxivaing().setSelectedItem("Sin IVA");
        ingvsgas.getjComboBoxivaeg().setSelectedItem("Sin IVA");

        //actualiza totales        
        ingvsgas.calculo_total_ing(ingvsgas.getTabla_ingresos());
        ingvsgas.calculo_total_eg(ingvsgas.getTabla_egresos());
        import_ingeg = true;

        Tabla.filas_defecto(ingvsgas.getTabla_ingresos(), 30);
        Tabla.filas_defecto(ingvsgas.getTabla_egresos(), 30);

        ingvsgas.setVisible(true);
    }//GEN-LAST:event_btn_IngVsGasMouseClicked

    private void btn_IngVsGasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IngVsGasMouseEntered
        // TODO add your handling code here:
        btn_IngVsGas.setForeground(Color.BLACK);
        panel_IngVsGas.setBackground(Color.WHITE);

    }//GEN-LAST:event_btn_IngVsGasMouseEntered

    private void btn_IngVsGasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IngVsGasMouseExited
        // TODO add your handling code here:
        btn_IngVsGas.setForeground(Color.WHITE);
        panel_IngVsGas.setBackground(Color.BLACK);

    }//GEN-LAST:event_btn_IngVsGasMouseExited

    private void btn_indicadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_indicadoresMouseClicked
        // TODO add your handling code here:
        ((DefaultTableModel) indicadores.getTabla_indicadores().getModel()).setRowCount(0);
        indicadores.setVisible(true);

        Tabla.inicializar(indicadores.getTabla_indicadores());
        Tabla.importar(indicadores.getIndicadores(), indicadores.getTabla_indicadores());
        //añade filas por defecto si no hay ninguna en la tabla
        Tabla.filas_defecto(indicadores.getTabla_indicadores(), 5);

    }//GEN-LAST:event_btn_indicadoresMouseClicked

    private void btn_indicadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_indicadoresMouseEntered
        // TODO add your handling code here:
        btn_indicadores.setForeground(Color.BLACK);
        panel_indicadores.setBackground(Color.WHITE);


    }//GEN-LAST:event_btn_indicadoresMouseEntered

    private void btn_indicadoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_indicadoresMouseExited
        // TODO add your handling code here:
        btn_indicadores.setForeground(Color.WHITE);
        panel_indicadores.setBackground(Color.BLACK);

    }//GEN-LAST:event_btn_indicadoresMouseExited

    private void btn_indicadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_indicadoresActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_indicadoresActionPerformed

    private void btn_EBITDAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EBITDAMouseClicked
        // TODO add your handling code here:

        ebitda.setVisible(true);
        Tabla.inicializar(ebitda.getTabla_ebitda());
        Tabla.importar(ebitda.getEbitda(), ebitda.getTabla_ebitda());
 
    }//GEN-LAST:event_btn_EBITDAMouseClicked

    private void btn_EBITDAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EBITDAMouseEntered
        // TODO add your handling code here:
        btn_EBITDA.setForeground(Color.BLACK);
        panel_EBITDA.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_EBITDAMouseEntered

    private void btn_EBITDAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EBITDAMouseExited
        // TODO add your handling code here:
        btn_EBITDA.setForeground(Color.WHITE);
        panel_EBITDA.setBackground(Color.BLACK);


    }//GEN-LAST:event_btn_EBITDAMouseExited

    private void btn_EBITDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EBITDAActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_EBITDAActionPerformed

    private void btn_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadosMouseClicked
        // TODO add your handling code here:
        Tabla.get_modelo(empleados.getTabla_tasas()).setRowCount(0);
        Tabla.importar(empleados.getTasas(), empleados.getTabla_tasas());
        Tabla.filas_defecto(empleados.getTabla_tasas(), 1);
        empleados.inicializar_combo();
        empleados.importar_emp();
        empleados.total_sueldos();
        empleados.antiguedad();
        empleados.presentismo();
        empleados.bruto();
        empleados.setImp_tas(true);
        empleados.tasas(empleados.getTas_jub());
        empleados.tasas(empleados.getTas_ob());
        empleados.tasas(empleados.getTas_ley());
        empleados.tasas(empleados.getTas_sec());
        empleados.total_desc();
        empleados.total_neto();
        empleados.setVisible(true);
    }//GEN-LAST:event_btn_empleadosMouseClicked

    private void btn_empleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadosMouseEntered
        // TODO add your handling code here:
        btn_empleados.setForeground(Color.BLACK);
        panel_empleados.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_empleadosMouseEntered

    private void btn_empleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadosMouseExited
        // TODO add your handling code here:
        btn_empleados.setForeground(Color.WHITE);
        panel_empleados.setBackground(Color.BLACK);

    }//GEN-LAST:event_btn_empleadosMouseExited

    private void btn_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_empleadosActionPerformed

    private void btn_impuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_impuestosMouseClicked
        // TODO add your handling code here:

        impuestos.setVisible(true);
        Tabla.inicializar(impuestos.getTabla_impuestos());
        Tabla.importar(impuestos.getImpuestos(), impuestos.getTabla_impuestos());
        Tabla.importar(impuestos.getIndimpuestos(), impuestos.getTabla_indimpuestos());
        //añade filas por defecto si no hay ninguna en la tabla
        impuestos.filas_datos_impuestos(impuestos.getTabla_impuestos(), impuestos.getTabla_indimpuestos());
    }//GEN-LAST:event_btn_impuestosMouseClicked

    private void btn_impuestosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_impuestosMouseEntered
        // TODO add your handling code here:
        btn_impuestos.setForeground(Color.BLACK);
        panel_impuestos.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_impuestosMouseEntered

    private void btn_impuestosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_impuestosMouseExited
        // TODO add your handling code here:
        btn_impuestos.setForeground(Color.WHITE);
        panel_impuestos.setBackground(Color.BLACK);

    }//GEN-LAST:event_btn_impuestosMouseExited

    private void btn_impuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_impuestosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_impuestosActionPerformed

    private void btn_creditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_creditoMouseClicked
        // TODO add your handling code here:

        credito.setVisible(true);
        Tabla.importar(credito.getPagcredito(), credito.getTabla_pagcredito());
        Tabla.importar(credito.getDatcredito(), credito.getTabla_datcredito());

        //añade filas por defecto si no hay ninguna en la tabla
        credito.filas_datos(credito.getTabla_datcredito(), credito.getTabla_pagcredito());
    }//GEN-LAST:event_btn_creditoMouseClicked

    private void btn_creditoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_creditoMouseEntered
        // TODO add your handling code here:
        btn_credito.setForeground(Color.BLACK);
        panel_credito.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_creditoMouseEntered

    private void btn_creditoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_creditoMouseExited
        // TODO add your handling code here:
        btn_credito.setForeground(Color.WHITE);
        panel_credito.setBackground(Color.BLACK);

    }//GEN-LAST:event_btn_creditoMouseExited

    private void btn_creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_creditoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_creditoActionPerformed

    private void panel_IngVsGasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_IngVsGasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_IngVsGasMouseClicked

    private void panel_IngVsGasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_IngVsGasMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_panel_IngVsGasMouseEntered

    private void panel_IngVsGasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_IngVsGasMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_IngVsGasMouseExited

    private void panel_EBITDAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_EBITDAMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_EBITDAMouseEntered

    private void panel_EBITDAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_EBITDAMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_EBITDAMouseExited

    private void panel_indicadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_indicadoresMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_indicadoresMouseEntered

    private void panel_indicadoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_indicadoresMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_indicadoresMouseExited

    private void panel_empleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_empleadosMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_empleadosMouseEntered

    private void panel_empleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_empleadosMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_empleadosMouseExited

    private void panel_impuestosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_impuestosMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_impuestosMouseEntered

    private void panel_impuestosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_impuestosMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_impuestosMouseExited

    private void panel_creditoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_creditoMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_creditoMouseEntered

    private void panel_creditoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_creditoMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_creditoMouseExited

    private void añosvidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añosvidaActionPerformed
        // TODO add your handling code here:
        // Se obtienen los años de vida del proyecto para las demas clases
        int longev = 5;
        try {
            longev = Integer.parseInt(añosvida.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor válido");
        }
        longevidad = longev;

        //inicializa ing y eg
        Tabla.inicializar(ingvsgas.getTabla_ingresos());
        Tabla.inicializar(ingvsgas.getTabla_egresos());

        //actualiza totales        
        ingvsgas.calculo_total_ing(ingvsgas.getTabla_ingresos());
        ingvsgas.calculo_total_eg(ingvsgas.getTabla_egresos());

    }//GEN-LAST:event_añosvidaActionPerformed

    private void añosvidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_añosvidaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_añosvidaPropertyChange

    private void btn_riesgoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_riesgoMouseClicked
        // TODO add your handling code here:
        riesgo.setVisible(true);
        Tabla.inicializar(riesgo.getTabla_riesgos());
        Tabla.importar(riesgo.getRiesgos(), riesgo.getTabla_riesgos());

    }//GEN-LAST:event_btn_riesgoMouseClicked

    private void btn_riesgoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_riesgoMouseEntered
        // TODO add your handling code here:
        btn_riesgo.setForeground(Color.BLACK);
        panel_riesgo.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_riesgoMouseEntered

    private void btn_riesgoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_riesgoMouseExited
        // TODO add your handling code here:
        btn_riesgo.setForeground(Color.WHITE);
        panel_riesgo.setBackground(Color.BLACK);
    }//GEN-LAST:event_btn_riesgoMouseExited

    private void btn_riesgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_riesgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_riesgoActionPerformed

    private void panel_riesgoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_riesgoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_riesgoMouseClicked

    private void panel_riesgoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_riesgoMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_riesgoMouseEntered

    private void panel_riesgoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_riesgoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_riesgoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelFondo;
    private javax.swing.JTextField añosvida;
    private javax.swing.JButton btn_EBITDA;
    private javax.swing.JButton btn_IngVsGas;
    private javax.swing.JButton btn_credito;
    private javax.swing.JButton btn_empleados;
    private javax.swing.JButton btn_impuestos;
    private javax.swing.JButton btn_indicadores;
    private javax.swing.JButton btn_riesgo;
    private javax.swing.JTextField nombreproyecto;
    private javax.swing.JPanel panel_EBITDA;
    private javax.swing.JPanel panel_IngVsGas;
    private javax.swing.JPanel panel_azul;
    private javax.swing.JPanel panel_azul_oscuro;
    private javax.swing.JPanel panel_credito;
    private javax.swing.JPanel panel_empleados;
    private javax.swing.JPanel panel_impuestos;
    private javax.swing.JPanel panel_indicadores;
    private javax.swing.JPanel panel_negro;
    private javax.swing.JPanel panel_riesgo;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtañosvida;
    private javax.swing.JLabel txtnombreproyecto;
    // End of variables declaration//GEN-END:variables

}
