/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import aplicacion.de.evaluacion.de.proyectos.ProjectEvaluator;
import java.awt.Color;
import java.io.File;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enzo
 */
public class Riesgo extends javax.swing.JFrame {

    /**
     * Creates new form Riesgo
     */
    private File riesgos = new File("C:\\Project evaluator\\riesgos.txt");
    private double prob;
    private double impacto;
    private double exposicion;
    private double valor;
    private boolean imp;

    public Riesgo() {
        initComponents();
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //determina el color del fondo
        Color c = new Color(56, 80, 113);
        getContentPane().setBackground(c);
        imp = false;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riesgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riesgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riesgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riesgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riesgo().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll_riesg = new javax.swing.JScrollPane();
        tabla_riesgos = new javax.swing.JTable();
        txtriesgos = new javax.swing.JLabel();
        btn_añadirfila_riesg = new javax.swing.JButton();
        btn_quitarfila_riesg = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(900, 690));

        tabla_riesgos.setBackground(new java.awt.Color(255, 255, 255));
        tabla_riesgos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Factor de Riesgo", "Categoría", "Probabilidad", "Impacto", "Exposición", "Efecto", "Valor", "Respuesta", "Valor Riesgo", "Contingencia", "Responsable", "Fecha Mitigación"
            }
        ));
        tabla_riesgos.setShowGrid(true);
        tabla_riesgos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabla_riesgosPropertyChange(evt);
            }
        });
        scroll_riesg.setViewportView(tabla_riesgos);

        txtriesgos.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        txtriesgos.setForeground(new java.awt.Color(240, 255, 255));
        txtriesgos.setText("Riesgos");

        btn_añadirfila_riesg.setText("añadir fila");
        btn_añadirfila_riesg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirfila_riesgActionPerformed(evt);
            }
        });

        btn_quitarfila_riesg.setText("quitar fila");
        btn_quitarfila_riesg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarfila_riesgActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll_riesg, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtriesgos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                        .addComponent(btn_añadirfila_riesg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_quitarfila_riesg)
                        .addGap(87, 87, 87)
                        .addComponent(btn_guardar)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_añadirfila_riesg)
                    .addComponent(btn_quitarfila_riesg)
                    .addComponent(txtriesgos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(scroll_riesg, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTabla_riesgos() {
        return tabla_riesgos;
    }

    public File getRiesgos() {
        return riesgos;
    }

    public void setImp(boolean imp) {
        this.imp = imp;
    }

    public void valor_riesgo() {
        try {
            for (int i = 0; i < tabla_riesgos.getRowCount(); i++) {
                double result = Double.valueOf(String.valueOf(tabla_riesgos.getValueAt(i, 5))) / 100 * Double.valueOf(String.valueOf(tabla_riesgos.getValueAt(i, 7)));
                tabla_riesgos.setValueAt(result, i, 9);
            }
        } catch (IndexOutOfBoundsException | NumberFormatException e) {

        }
    }

    private void btn_añadirfila_riesgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirfila_riesgActionPerformed
        // TODO add your handling code here
        //Añade filas a ingresos
        Vector<?> rowData = null;
        ProjectEvaluator.Tabla.get_modelo(tabla_riesgos).addRow(rowData);
    }//GEN-LAST:event_btn_añadirfila_riesgActionPerformed

    private void btn_quitarfila_riesgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarfila_riesgActionPerformed
        // TODO add your handling code here:
        //Quita filas a idicadores, si no se selecciona una fila,se elimina la ultima
        if (tabla_riesgos.getSelectedRowCount() == 1) {
            ProjectEvaluator.Tabla.get_modelo(tabla_riesgos).removeRow(tabla_riesgos.getSelectedRow());
        } else {
            ProjectEvaluator.Tabla.get_modelo(tabla_riesgos).removeRow(tabla_riesgos.getRowCount() - 1);
        }
    }//GEN-LAST:event_btn_quitarfila_riesgActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:

        try {
            ProjectEvaluator.Tabla.exportar(riesgos, tabla_riesgos);
            JOptionPane.showMessageDialog(null, "datos guardados");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al guardar los datos");
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void tabla_riesgosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabla_riesgosPropertyChange
        // TODO add your handling code here:

        if (imp == true) {
            try {
                valor_riesgo();
                ProjectEvaluator.Tabla.exportar(riesgos, tabla_riesgos);
            } catch (Exception e) {
                System.out.println("Error en guardado de datos (Riesgo)");
            }
        }
    }//GEN-LAST:event_tabla_riesgosPropertyChange

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadirfila_riesg;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_quitarfila_riesg;
    private javax.swing.JScrollPane scroll_riesg;
    private javax.swing.JTable tabla_riesgos;
    private javax.swing.JLabel txtriesgos;
    // End of variables declaration//GEN-END:variables
}
